dataset_type: "RSNAChallengeBinary"
base_path: "C:\\data\\RSNA_challenge"
class_names: ["Class0", "Class1"]
# CV splitting
data_split_file: "C:\\sources\\my_dl_framework\\cv_splits\\cv_split_3fold.json"
run_cv_subset: [0, 1, 2]  # Specify a subset of CV splits to train
csv_name: "stage_2_train_labels.csv"
training_image_dir: "training_images"
# Training settings
batch_size: 16
lr_scheduler: "stepwise"
step_size: 50
lr_step: 2
num_epochs: 4
optimizer: "Adam"
learning_rate: 0.00005
loss_name: "cross_entropy"
loss_log_freq: 5
num_batch_examples: 2
# Model settings
classification_model_name: "densenet121"
pretrained: True
num_classes: 2
preload_images: False
resize_images: 256
random_crop: 224
random_fliplr: True
color_jitter: True
continue_training: null  # null or the timestamp
continue_training_from_clearml: null # null or clearml ID
ckpt_every_n_epochs: 1
# Inference
apply_center_crop_inf: True
multi_crop_eval: None  # e.g. 3->9 crops
# Validation settings:
validate_every_x_epochs: 1
validate_on_train_set: False
test_aug_ensemble_mode: mean
max_num_batches_val: 10
val_best_metric: auc_score_mean
val_best_target: max
