name: Python tests
on:
  pull_request:
    branches: [develop, main]
  push:
    branches: [develop, main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          python setup.py develop
      - name: Pylint
        run: pylint --fail-under=5.0 my_dl_framework
      - name: Dependencies
        run:  pip-licenses
      - name: Test with pytest
        run: |
          pytest --cov-report xml --cov=my_dl_framework tests/
